#!/bin/sh -x
#lastfmplayer - simple scrobbling mplayer wrapper
#
#Copyright (C) [2010] [Sven Schober]
#
#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful, but
#WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, see <http://www.gnu.org/licenses/>.
#
#
# Prerequisites:
#	* Get and setup http://www.red-bean.com/~decklin/software/lastfmsubmitd/
#	* perl-music-tag-{mp3,m4a} (Archlinux package names)
#
# Install this script with some handy name, e.g. '/usr/local/bin/m'.
#
# Known problems:
#	* 'q' interrupts only playback of current file; press and *hold* ctrl-C
#	* even if you skip file immediately with Enter or 'q', it gets scrobbled - see below
#
# Song info will be submitted after you finish listening to the song;
# if you are SKIPPING a track and don't want it to appear, press Ctrl-C
# in mplayer - it will skip to the next track without scrobbling.

# ([ -f var/run/lastfm/lastfmsubmitd.pid ] && kill -0 `cat /var/run/lastfm/lastfmsubmitd.pid` 2>&1) || lastfmsubmitd
[ "$LASTFM_PLAYER" ] || LASTFM_PLAYER=/usr/bin/mplayer
[ "$MUSICTAG" ] || MUSICTAG=musictag
[ "$LASTFM_SUBMIT" ] || LASTFM_SUBMIT=/usr/lib/lastfmsubmitd/lastfmsubmit

scrobble () {
	read album;
	read artist;
	read time;
	read title;
	[ "$album" = "1" ] && album=""
    seconds=$(echo "$time / 1000" | bc)

	echo "## Last.FM : -l \"$seconds\" -a \"$artist\" -b \"$album\" --title \"$title\""

	$LASTFM_SUBMIT -e utf8 \
		-l "$seconds" -a "$artist" -b "$album" --title "$title"
}

for f; do
	case "$f" in
	*.mp3 | *.m4a)
		$MUSICTAG --printinfo "$f" \
		|  grep "ALBUM\|DURATION\|ARTIST\|TITLE"  \
		|  sed -e "s;';;g" -e "s;.*=>\(.*\),$;\1;" \
		|  scrobble
		;;
	esac

	$LASTFM_PLAYER "$f" || continue
done
